site_name: Sandeep Suman
site_description: 'Assistant Professor, TMBU, Bhagalpur'
site_author: 'Sandeep Suman'
site_url: 'https://sandeepsuman.com/'

plugins:
  - search
  - table-reader
  - minify:
      minify_html: true

  - add-number:
      strict_mode: False
      order: 2
      excludes:
        - index.md


theme:
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  name: material
  custom_dir: 'theme'
  features:
    - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  font:
    text: Roboto
    code: Roboto Mono
  favicon: static/images/favicon.ico
  icon:
    logo: logo

  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt


  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  static_templates:
    - 404.html
    
  favicon: 'static/images/favicon.ico'

markdown_extensions:
  - admonition
  # - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes

  - mdx_math: # pip install python-markdown-math
      enable_dollar_delimiter: true

  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

  - meta      

extra_javascript:
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'static/js/app.js'

extra_css:
  - 'static/stylesheets/extra.css' # depends on theme


google_analytics: ['UA-140256543-1', 'sandeepsuman.com']

# Copyright
copyright: 'Copyright &copy; 2016 - 2023 <a href="https://sandeepsuman.com">Sandeep Suman</a>'

# Page tree
nav:
  - Home: index.md
  - Linear Algebra:
    - Course Overview: linear-algebra/introduction.md
    - 'Linear Equations': linear-algebra/linear-equations.md
    - 'Matrix of Linear Transformation': linear-algebra/matrix-linear-transformation.md
    - Assignment: linear-algebra/assignments.md
    - Exam: linear-algebra/exam.md
    - 21-23: linear-algebra/21-23.md
  - C Programming:
    - Course Overview: programming-in-c/introduction.md
    - Programming: programming-in-c/programming.md
    - Feature of C: programming-in-c/feature.md